#!/usr/bin/env python
#filetype: py

import os
import sys
import scripts.databases as databases

shell.prefix("unset pipefail; ")
configfile: "../config/config.yaml"
merge_config = 1


# Gene Ontology
include: "rules/go.smk"
# Human Phenotype Ontology
include: "rules/hpo.smk"
# Mondo  
include: "rules/mondo.smk"
# Ensembl Genes (or NCBI??) 
include: "rules/ensembl.smk"
#Uniprot
include: "rules/uniprot.smk"
# RNACentral ncRNAs
include: "rules/rnacentral.smk"
# RO
include: "rules/ro.smk"
#GOA
include: "rules/goa.smk"
#HPOA
include: "rules/hpoa.smk"
# Disgenet
include: "rules/disgenet.smk"
#Uberon
include: "rules/uberon.smk"
#Cell Ontology
include: "rules/cl.smk"
#Bgee
include: "rules/bgee.smk"
#Mirtarbase
include: "rules/mirtarbase.smk"
#NPInter
include: "rules/npinter.smk"
#String
include: "rules/stringdb.smk"


rule all:
    input: "../data/processed/finals/lcc_nodes.tsv", "../data/processed/finals/lcc_nodes.tsv"

rule gather_data:
    input: databases.get_input_files()
    output: "../data/processed/finals/merged_nodes.tsv", "../data/processed/finals/merged_edges.tsv"
    shell: "kgx merge --merge-config ../config/merge_config.yaml"

rule find_lcc:
    input: nodes="../data/processed/finals/merged_nodes.tsv", edges="../data/processed/finals/merged_edges.tsv"
    output: "../data/processed/finals/lcc_nodes.tsv", "../data/processed/finals/lcc_edges.tsv"
    shell: "python scripts/lcc.py -n {input.nodes} -e {input.edges} -o ../data/processed/finals/lcc "
