classes:
  - class: biolink:Gene
    database: ENSEMBL
  - class: biolink:Protein
    database: UNIPROTKB
  - class: biolink:RNA
    database: RNACENTRAL
  - class: biolink:MacromolecularComplexMixin
    database: COMPLEXPORTAL
  - class: biolink:Disease
    database: MONDO
  - class: biolink:PhenotypicFeature
    database: HP
  - class: biolink:AnatomicalEntity
    database: BGEE
  - class: biolink:AnatomicalEntity
    database: UBERON

edges_relations:
  - category: biolink:FunctionalAssociation
    object: GO
  - category: biolink:GeneToPhenotypicFeatureAssociation
    object: HP
    predicate: biolink:associated_with
    relation: RO:0016001
    subject: ENSEMBL
  - category: biolink:GeneToDiseaseAssociation
    object: MONDO
    predicate: biolink:associated_with
    relation: RO:0016001
    subject: ENSEMBL
  - object: UNIPROTKB
    predicate: biolink:has_gene_product
    relation: RO:0002205
    subject: ENSEMBL
  - object: RNACENTRAL
    predicate: biolink:has_gene_product
    relation: RO:0002205
    subject: ENSEMBL
  - category: biolink:DiseaseToPhenotypicFeatureAssociation
    object: HP
    predicate: biolink:has_phenotype
    relation: RO:0002200
    subject: OMIM
  - category: biolink:DiseaseToPhenotypicFeatureAssociation
    object: HP
    predicate: biolink:has_phenotype
    relation: RO:0002200
    subject: DECIPHER
  - category: biolink:DiseaseToPhenotypicFeatureAssociation
    object: HP
    predicate: biolink:has_phenotype
    relation: RO:0002200
    subject: ORPHA
  - category: biolink:GeneToExpressionSiteAssociation
    object: CL
    predicate: biolink:expressed_in
    relation: RO:0002206
    subject: ENSEMBL

