#COMMENT DATABASES AND FILTERS NOT BE INCLUDED ON MERGE FILE
databases:
  - source: gene_ontology
    name: GO
    nodes: "../data/processed/finals/go_nodes.tsv"
    edges: "../data/processed/finals/go_edges.tsv"
    filters:
      node_filters:
        category:
          - biolink:BiologicalProcess
          - biolink:CellularComponent
          - biolink:MolecularActivity
          - biolink:OntologyClass
      edge_filters:
        predicate:
            - biolink:has_part
            - biolink:negatively_regulates
            - biolink:occurs_in
            - biolink:part_of
            - biolink:positively_regulates
            - biolink:regulates
            - biolink:related_to
            - biolink:subclass_of
  - source: human_phenotype_ontology
    name: HP
    nodes: "../data/processed/finals/hpo_nodes.tsv"
    edges: "../data/processed/finals/hpo_edges.tsv"
    filters:
      node_filters:
        category:
          - biolink:MolecularActivity
#          - biolink:OntologyClass
          - biolink:PhenotypicFeature
      edge_filters:
        predicate:
          - biolink:subclass_of
  - source: mondo
    name: MONDO
    nodes: "../data/processed/finals/mondo_nodes.tsv"
    edges: "../data/processed/finals/mondo_edges.tsv"
    filters:
      node_filters:
        category:
          - biolink:AnatomicalEntity
          - biolink:BiologicalProcess
          - biolink:Cell
          - biolink:CellularComponent
#          - biolink:ChemicalSubstance
          - biolink:Disease
          - biolink:MolecularActivity
#          - biolink:NamedThing
#          - biolink:OntologyClass
#          - biolink:OrganismalEntity
          - biolink:PhenotypicFeature
#          - biolink:SequenceFeature
      edge_filters:
        predicate:
          - biolink:actively_involved_in
          - biolink:acts_upstream_of
          - biolink:acts_upstream_of_negative_effect
          - biolink:acts_upstream_of_or_within
          - biolink:acts_upstream_of_or_within_negative_effect
          - biolink:acts_upstream_of_or_within_positive_effect
          - biolink:acts_upstream_of_positive_effect
          - biolink:affects
          - biolink:affects_localization_of
          - biolink:associated_with
          - biolink:capable_of
          - biolink:caused_by
          - biolink:causes
          - biolink:coexists_with
          - biolink:colocalizes_with
          - biolink:contributes_to
          - biolink:derives_from
          - biolink:develops_from
          - biolink:disrupts
          - biolink:enables
          - biolink:expresses
          - biolink:has_attribute
          - biolink:has_gene_product
          - biolink:has_input
          - biolink:has_output
          - biolink:has_part
          - biolink:has_participant
          - biolink:has_phenotype
          - biolink:homologous_to
#          - biolink:in_taxon
          - biolink:increases_degradation_of
          - biolink:interacts_with
          - biolink:involved_in
          - biolink:located_in
          - biolink:location_of
#          - biolink:model_of
          - biolink:negatively_regulates
          - biolink:occurs_in
          - biolink:overlaps
#          - biolink:part_of
          - biolink:participates_in
          - biolink:positively_regulates
          - biolink:preceded_by
          - biolink:precedes
          - biolink:produced_by
          - biolink:produces
          - biolink:regulates
          - biolink:related_to
#          - biolink:subclass_of
#          - biolink:temporally_related_to
#          - biolink:type
  - source: ensembl
    name: ENSEMBL
    nodes: "../data/processed/finals/ensembl_nodes.tsv"
    edges: "../data/processed/finals/ensembl_edges.tsv"
    filters:
      node_filters:
        category:
          - biolink:Gene
          - biolink:Protein
      edge_filters:
        predicate:
          - biolink:has_gene_product
  - source: gene_ontology_annotation
    name: GOA
    nodes: "../data/processed/finals/goa_nodes.tsv"
    edges: "../data/processed/finals/goa_edges.tsv"
    filters:
      node_filters:
        category:
          - biolink:RNA
          - biolink:Protein
          - biolink:MacromolecularComplexMixin
          - biolink:BiologicalProcess
          - biolink:CellularComponent
          - biolink:MolecularActivity
          - biolink:OntologyClass
      edge_filters:
        predicate:
          - biolink:active_in
          - biolink:acts_upstream_of
          - biolink:acts_upstream_of_negative_effect
          - biolink:acts_upstream_of_or_within
          - biolink:acts_upstream_of_or_within_negative_effect
          - biolink:acts_upstream_of_or_within_positive_effect
          - biolink:acts_upstream_of_positive_effect
#          - biolink:colocalizes_with
          - biolink:contributes_to
          - biolink:enables
          - biolink:involved_in
          - biolink:located_in
#          - biolink:part_of
  - source: human_phenotype_ontology_annotation
    name: HPOA
    nodes: "../data/processed/finals/hpoa_nodes.tsv"
    edges: "../data/processed/finals/hpoa_edges.tsv"
    filters:
      node_filters:
        category:
          - biolink:Disease
          - biolink:PhenotypicFeature
      edge_filters:
        predicate:
          - biolink:has_phenotype
  - source: disgenet
    name: Disgenet
    nodes: "../data/processed/finals/disgenet_nodes.tsv"
    edges: "../data/processed/finals/disgenet_edges.tsv"
    filters:
      node_filters:
        category:
          - biolink:Gene
          - biolink:Disease
          - biolink:PhenotypicFeature
      edge_filters:
        predicate:
          - biolink:associated_with
  - source: uberon
    name: Uberon
    nodes: "../data/processed/finals/uberon_nodes.tsv"
    edges: "../data/processed/finals/uberon_edges.tsv"
    filters:
      node_filters:
        category:
#          - biolink:OntologyClass
          - biolink:AnatomicalEntity
          - biolink:Cell
      edge_filters:
        predicate:
#          - biolink:subclass_of
#          - biolink:part_of
          - biolink:related_to
          - biolink:has_part
          - biolink:develops_from
          - biolink:overlaps
          - biolink:coexists_with
          - biolink:causes
#          - biolink:subPropertyOf
          - biolink:located_in
          - biolink:temporally_related_to
          - biolink:inverseOf
          - biolink:produces
          - biolink:produced_by
          - biolink:preceded_by
          - biolink:location_of
          - biolink:precedes
          - biolink:homologous_to
  - source: cell_ontology
    name: CL
    nodes: "../data/processed/finals/cl_nodes.tsv"
    edges: "../data/processed/finals/cl_edges.tsv"
    filters:
      node_filters:
        category:
          - biolink:BiologicalProcess
          - biolink:MolecularActivity
          - biolink:CellularComponent
#          - biolink:OntologyClass
          - biolink:AnatomicalEntity
          - biolink:Cell
          - biolink:Protein
#          - biolink:ChemicalSubstance
#          - biolink:OrganismalEntity
#          - biolink:NamedThing
      edge_filters:
        predicate:
#          - biolink:subclass_of
#          - biolink:part_of
          - biolink:related_to
          - biolink:has_part
          - biolink:has_output
          - biolink:regulates
          - biolink:develops_from
          - biolink:negatively_regulates
          - biolink:positively_regulates
          - biolink:overlaps
          - biolink:has_input
          - biolink:coexists_with
#          - biolink:in_taxon
          - biolink:capable_of
          - biolink:causes
          - biolink:subPropertyOf
          - biolink:located_in
          - biolink:has_attribute
          - biolink:occurs_in
          - biolink:affects
          - biolink:participates_in
          - biolink:has_participant
          - biolink:temporally_related_to
          - biolink:inverseOf
          - biolink:expresses
          - biolink:produces
          - biolink:caused_by
          - biolink:produced_by
          - biolink:interacts_with
          - biolink:preceded_by
          - biolink:location_of
          - biolink:increases_degradation_of
          - biolink:precedes
          - biolink:homologous_to
          - biolink:affects_localization_of
          - biolink:derives_from
  - source: bgee
    name: Bgee
    nodes: "../data/processed/finals/bgee_nodes.tsv"
    edges: "../data/processed/finals/bgee_edges.tsv"
    filters:
      node_filters:
        category:
          - biolink:AnatomicalEntity
          - biolink:Cell
          - biolink:Gene
      edge_filters:
        predicate:
          - biolink:expressed_in
  - source: rnacentral
    name: RNACentral
    nodes: "../data/processed/finals/rnacentral_nodes.tsv"
    edges: "../data/processed/finals/rnacentral_edges.tsv"
    filters:
      node_filters:
        category:
          - biolink:Gene
          - biolink:RNA
      edge_filters:
        predicate:
          - biolink:has_gene_product
  - source: mirtarbase
    name: Mirtarbase
    nodes: "../data/processed/finals/mirtarbase_nodes.tsv"
    edges: "../data/processed/finals/mirtarbase_edges.tsv"
    filters:
      node_filters:
        category:
          - biolink:RNA
          - biolink:Gene
      edge_filters:
        predicate:
          - biolink:interacts_with
  - source: npinter
    name: NPInter
    nodes: "../data/processed/finals/npinter_nodes.tsv"
    edges: "../data/processed/finals/npinter_edges.tsv"
    filters:
      node_filters:
        category:
          - biolink:RNA
          - biolink:Gene
          - biolink:Protein
      edge_filters:
        predicate:
          - biolink:binds
          - biolink:regulates
          - biolink:correlates
          - biolink:coexpressed_with
  - source: string
    name: STRING
    nodes: "../data/processed/finals/string_nodes.tsv"
    edges: "../data/processed/finals/string_edges.tsv"
    filters:
      node_filters:
        category:
          - biolink:Protein
      edge_filters:
        predicate:
          - biolink:interacts_with
