configuration:
  checkpoint: false
  output_directory: ../data/processed/finals
merged_graph:
  destination:
    merged-kg-tsv:
      compression: gz
      filename: merged
      format: tsv
  name: KG
  operations:
    - args:
        edge_facet_properties:
          - knowledge_source
        filename: ../data/processed/finals/merged_graph_stats.yaml
        graph_name: KG
        node_facet_properties:
          - provided_by
      name: kgx.graph_operations.summarize_graph.generate_graph_stats
  source:
    bgee:
      input:
        filename:
          - ../data/processed/finals/bgee_nodes.tsv
          - ../data/processed/finals/bgee_edges.tsv
        filters:
          edge_filters:
            predicate:
              - biolink:expressed_in
          node_filters:
            category:
              - biolink:AnatomicalEntity
              - biolink:Cell
              - biolink:Gene
        format: tsv
        name: Bgee
    cell_ontology:
      input:
        filename:
          - ../data/processed/finals/cl_nodes.tsv
          - ../data/processed/finals/cl_edges.tsv
        filters:
          edge_filters:
            predicate:
              - biolink:subclass_of
              - biolink:inverseOf
              - biolink:subPropertyOf
              - biolink:related_to
          node_filters:
            category:
              - biolink:BiologicalProcess
              - biolink:MolecularActivity
              - biolink:CellularComponent
              - biolink:AnatomicalEntity
              - biolink:Cell
              - biolink:Protein
        format: tsv
        name: CL
    disgenet:
      input:
        filename:
          - ../data/processed/finals/disgenet_nodes.tsv
          - ../data/processed/finals/disgenet_edges.tsv
        filters:
          edge_filters:
            predicate:
              - biolink:associated_with
          node_filters:
            category:
              - biolink:Gene
              - biolink:Disease
              - biolink:PhenotypicFeature
        format: tsv
        name: Disgenet
    ensembl:
      input:
        filename:
          - ../data/processed/finals/ensembl_nodes.tsv
          - ../data/processed/finals/ensembl_edges.tsv
        filters:
          edge_filters:
            predicate:
              - biolink:has_gene_product
          node_filters:
            category:
              - biolink:Gene
              - biolink:Protein
        format: tsv
        name: ENSEMBL
    gene_ontology:
      input:
        filename:
          - ../data/processed/finals/go_nodes.tsv
          - ../data/processed/finals/go_edges.tsv
        filters:
          edge_filters:
            predicate:
              - biolink:subclass_of
              - biolink:related_to
              - biolink:inverseOf
              - biolink:subPropertyOf
          node_filters:
            category:
              - biolink:BiologicalProcess
              - biolink:CellularComponent
              - biolink:MolecularActivity
        format: tsv
        name: GO
    gene_ontology_annotation:
      input:
        filename:
          - ../data/processed/finals/goa_nodes.tsv
          - ../data/processed/finals/goa_edges.tsv
        filters:
          edge_filters:
            predicate:
              - biolink:active_in
              - biolink:acts_upstream_of
              - biolink:acts_upstream_of_negative_effect
              - biolink:acts_upstream_of_or_within
              - biolink:acts_upstream_of_or_within_negative_effect
              - biolink:acts_upstream_of_or_within_positive_effect
              - biolink:acts_upstream_of_positive_effect
              - biolink:colocalizes_with
              - biolink:contributes_to
              - biolink:enables
              - biolink:involved_in
              - biolink:located_in
              - biolink:part_of
          node_filters:
            category:
              - biolink:RNA
              - biolink:Protein
              - biolink:MacromolecularComplexMixin
              - biolink:BiologicalProcess
              - biolink:CellularComponent
              - biolink:MolecularActivity
        format: tsv
        name: GOA
    human_phenotype_ontology:
      input:
        filename:
          - ../data/processed/finals/hpo_nodes.tsv
          - ../data/processed/finals/hpo_edges.tsv
        filters:
          edge_filters:
            predicate:
              - biolink:subclass_of
          node_filters:
            category:
              - biolink:PhenotypicFeature
        format: tsv
        name: HP
    human_phenotype_ontology_annotation:
      input:
        filename:
          - ../data/processed/finals/hpoa_nodes.tsv
          - ../data/processed/finals/hpoa_edges.tsv
        filters:
          edge_filters:
            predicate:
              - biolink:has_phenotype
          node_filters:
            category:
              - biolink:Disease
              - biolink:PhenotypicFeature
        format: tsv
        name: HPOA
    mirtarbase:
      input:
        filename:
          - ../data/processed/finals/mirtarbase_nodes.tsv
          - ../data/processed/finals/mirtarbase_edges.tsv
        filters:
          edge_filters:
            predicate:
              - biolink:interacts_with
          node_filters:
            category:
              - biolink:RNA
              - biolink:Gene
        format: tsv
        name: Mirtarbase
    mondo:
      input:
        filename:
          - ../data/processed/finals/mondo_nodes.tsv
          - ../data/processed/finals/mondo_edges.tsv
        filters:
          edge_filters:
            predicate:
              - biolink:type
              - biolink:subclass_of
              - biolink:subPropertyOf
              - biolink:inverseOf
              - biolink:related_to
          node_filters:
            category:
              - biolink:AnatomicalEntity
              - biolink:BiologicalProcess
              - biolink:Cell
              - biolink:CellularComponent
              - biolink:Disease
              - biolink:MolecularActivity
              - biolink:PhenotypicFeature
        format: tsv
        name: MONDO
    npinter:
      input:
        filename:
          - ../data/processed/finals/npinter_nodes.tsv
          - ../data/processed/finals/npinter_edges.tsv
        filters:
          edge_filters:
            predicate:
              - biolink:binds
              - biolink:regulates
              - biolink:correlates
              - biolink:coexpressed_with
          node_filters:
            category:
              - biolink:RNA
              - biolink:Gene
              - biolink:Protein
        format: tsv
        name: NPInter
    rnacentral:
      input:
        filename:
          - ../data/processed/finals/rnacentral_nodes.tsv
          - ../data/processed/finals/rnacentral_edges.tsv
        filters:
          edge_filters:
            predicate:
              - biolink:has_gene_product
          node_filters:
            category:
              - biolink:Gene
              - biolink:RNA
        format: tsv
        name: RNACentral
    string:
      input:
        filename:
          - ../data/processed/finals/string_nodes.tsv
          - ../data/processed/finals/string_edges.tsv
        filters:
          edge_filters:
            predicate:
              - biolink:interacts_with
          node_filters:
            category:
              - biolink:Protein
        format: tsv
        name: STRING
    uberon:
      input:
        filename:
          - ../data/processed/finals/uberon_nodes.tsv
          - ../data/processed/finals/uberon_edges.tsv
        filters:
          edge_filters:
            predicate:
              - biolink:subPropertyOf
              - biolink:inverseOf
              - biolink:subclass_of
              - biolink:related_to
          node_filters:
            category:
              - biolink:AnatomicalEntity
              - biolink:Cell
        format: tsv
        name: Uberon
